require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'spec/dummy/**/*'
    - 'vendor/bundle/**/*'

Rails:
  Enabled: true

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 15

Metrics/ClassLength:
  Max: 150

Style/Documentation:
  Enabled: false
